# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fafc4457141163b99d0bc7f4c6c88cf5e54557de5df6e9157c74df6fa8d05e562988d2e3af50df782a14fe349fb9492a99bf7de1a70237c95df57ed254b95920

test:
  secret_key_base: f8fc2ec85660594960cd772aca0daca352effebeecd4d51cec3793647937589709d691692977047f99dfc90bc342c9e1bc5d9cd04e0453b84bcf9c02449735c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
